spring.application.name=librarydb
# URI de conexion a tu cluster de MongoDB Atlas
# Reemplaza <username>, <password> y <cluster-url> por los datos reales de tu cluster
spring.data.mongodb.uri=mongodb+srv://user1:user1@cluster0.ejdgtnt.mongodb.net/librarydb?appName=Cluster0



